apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: github-action-deployment
  name: github-action-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-action-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: github-action-deployment
    spec:
      containers:
      - image: harbor.jkolaric.eu/tbs/custom-afklm-packages-from-github-actions:latest
        name: custom-afklm-packages-from-github-actions
        resources: {}
status: {}
