---
name: supply-chain

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Source Provider
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Build Image
        id: build
        uses: vmware-tanzu/build-image-action@v1-alpha
        with:
          # auth
          server: ${{ secrets.SERVER }}
          token: ${{ secrets.TOKEN }}
          ca_cert: ${{ secrets.CA_CERT }}
          namespace: ${{ secrets.NAMESPACE }}
          # image config
          destination: harbor.jkolaric.eu/tbs/github-actions-did-it-twice
          # cluster builder config
          clusterbuilder: custom-afklm-packages
          #env: |
            #BP_JAVA_VERSION=17
    
      - name: Do something with image
        run: |
          if [ "${{ steps.build.outputs.name }}" == "" ]; then
            echo "::error::No output from previous step"
            exit 1
          fi
    
