---
name: supply-chain

on:
  push:
    branches:
      - main
  #pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Source Provider
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Build Image
        id: build
        uses: vmware-tanzu/build-image-action@v1-alpha
        with:
          # auth
          server: ${{ secrets.SERVER }}
          token: ${{ secrets.TOKEN }}
          ca_cert: ${{ secrets.CA_CERT }}
          namespace: ${{ secrets.NAMESPACE }}
          # image config
          destination: harbor.jkolaric.eu/tbs/github-actions-did-it-twice:1.1
          # cluster builder config
          clusterbuilder: custom-afklm-packages
          env: |
            BP_JAVA_VERSION=17
  
      - name: Do something with image
        run: |
          if [ "${{ steps.build.outputs.name }}" == "" ]; then
            echo "::error::No output from previous step"
            exit 1
          fi

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v2
        with:
          method: service-account
          k8s-url: ${{ secrets.SERVER }}
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}
            
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v1
        with:
          namespace: default
          manifests: |
            kubernetes/deployment.yaml
            #kubernetes/ingress.yaml
            kubernetes/service.yaml
          images: |
            harbor.jkolaric.eu/tbs/github-actions-did-it-twice:1.1
